"use client";
import { useEffect,useMemo,useState } from "react";
import { createClient } from "@/lib/supabase-client";
import { Activity,CalendarDays,CheckCircle2,Home,RefreshCw,Search,ShoppingBasket,Users,UserRoundCheck,Share2 } from "lucide-react";

type User={id:string;email:string|null;firstName:string;joinedAt:string;lastSignInAt:string|null;lastActivity:string|null;households:{id:string;name:string;role:string}[]};
type Household={id:string;name:string;createdAt:string;lastActivity:string|null;members:{id:string;userId:string;firstName:string;role:string;email:string|null}[];tasks30:number;shopping30:number;events30:number};
type Data={generatedAt:string;admin:string;kpis:Record<string,number>;recentHouseholds:{id:string;name:string;created_at:string;members:number}[];users:User[];households:Household[]};
const labels:Record<string,[string,string]>={users:["Utilisateurs","Comptes présents dans au moins un foyer"],households:["Foyers","Foyers créés au total"],activeHouseholds30:["Foyers actifs · 30 j","Activité tâche, course, calendrier ou contribution"],newUsers30:["Nouveaux · 30 j","Utilisateurs arrivés sur les 30 derniers jours"],multiHouseholdUsers:["Utilisateurs multi-foyers","Présents dans au moins deux foyers"],tasksCompleted30:["Tâches terminées · 30 j","Valeur réellement accomplie"],shoppingBought30:["Courses achetées · 30 j","Articles marqués achetés"],eventsCreated30:["Événements créés · 30 j","Usage du calendrier"],shares30:["Partages déclenchés · 30 j","Faire connaître DABO : partage natif ou copie du lien"],shareUsers30:["Ambassadeurs · 30 j","Utilisateurs uniques ayant partagé DABO"],sharesTotal:["Partages · total","Partages enregistrés depuis l’activation de la mesure"]};
const icons=[Users,Home,Activity,UserRoundCheck,Users,CheckCircle2,ShoppingBasket,CalendarDays,Share2,Users,Share2];
const fmt=(v:string|null)=>v?new Date(v).toLocaleDateString("fr-BE"):"—";
const active30=(v:string|null)=>!!v&&new Date(v).getTime()>=Date.now()-30*86400000;

export default function AdminPage(){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[tab,setTab]=useState<"overview"|"users"|"households">("overview"),[q,setQ]=useState("");
 const load=async()=>{setLoading(true);setError("");const supabase=createClient();const {data:s}=await supabase.auth.getSession();if(!s.session){location.href="/";return;}const r=await fetch("/api/admin/dashboard",{headers:{Authorization:`Bearer ${s.session.access_token}`}});const j=await r.json();if(!r.ok)setError(j.error||"Erreur");else setData(j);setLoading(false)};
 useEffect(()=>{load()},[]);
 const users=useMemo(()=>data?.users.filter(u=>(u.firstName+" "+(u.email||"")+" "+u.households.map(h=>h.name).join(" ")).toLowerCase().includes(q.toLowerCase()))||[],[data,q]);
 const homes=useMemo(()=>data?.households.filter(h=>(h.name+" "+h.members.map(m=>m.firstName+" "+(m.email||"")).join(" ")).toLowerCase().includes(q.toLowerCase()))||[],[data,q]);
 return <main className="min-h-screen bg-[#E7E3D8] text-ink"><header className="border-b border-border bg-paper"><div className="max-w-6xl mx-auto px-5 py-5 flex items-center justify-between gap-4"><div><div className="font-mono text-xs uppercase tracking-[.18em] text-mustard">DABO · Back-office</div><h1 className="font-serif text-3xl mt-1">Cockpit administrateur</h1></div><a href="/app" className="text-sm border border-border rounded-xl px-4 py-2 bg-white2">Retour à DABO</a></div><nav className="max-w-6xl mx-auto px-5 flex gap-6 overflow-x-auto">{[["overview","Vue d’ensemble"],["users","Utilisateurs"],["households","Foyers"]].map(([id,label])=><button key={id} onClick={()=>{setTab(id as typeof tab);setQ("")}} className={`py-3 text-sm whitespace-nowrap border-b-2 ${tab===id?"border-mustard font-semibold":"border-transparent text-muted"}`}>{label}</button>)}</nav></header>
 <div className="max-w-6xl mx-auto px-5 py-8"><div className="flex justify-between gap-4 items-end mb-7"><div><h2 className="font-serif text-2xl">{tab==="overview"?"Vue d’ensemble":tab==="users"?"Utilisateurs":"Foyers"}</h2><p className="text-muted text-sm mt-1">{tab==="overview"?"Pilotage produit et premiers indicateurs de traction.":tab==="users"?"Comptes DABO, foyers et activité récente.":"Composition et activité des foyers DABO."}</p></div><button onClick={load} className="flex gap-2 items-center text-sm"><RefreshCw size={15}/>Actualiser</button></div>
 {loading&&<div className="bg-paper border border-border rounded-2xl p-6">Chargement…</div>}{error&&<div className="bg-paper border border-border rounded-2xl p-6"><b>Accès impossible.</b><p className="text-sm text-muted mt-2">{error}</p></div>}
 {data&&tab==="overview"&&<><section className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">{Object.keys(labels).map((key,i)=>{const Icon=icons[i];return <article key={key} className="bg-paper border border-border rounded-2xl p-5"><div className="flex justify-between"><Icon size={19} className="text-mustard"/><span className="font-mono text-xs text-muted">KPI</span></div><div className="font-serif text-4xl mt-5">{data.kpis[key]??0}</div><div className="font-medium mt-2">{labels[key][0]}</div><p className="text-xs text-muted mt-1 leading-relaxed">{labels[key][1]}</p></article>})}</section><section className="grid lg:grid-cols-[1.4fr_.6fr] gap-5 mt-6"><article className="bg-paper border border-border rounded-2xl p-5"><h3 className="font-serif text-xl">Foyers récents</h3><div className="mt-4 divide-y divide-border">{data.recentHouseholds.map(h=><div key={h.id} className="py-3 flex justify-between gap-3"><div><div className="font-medium">{h.name}</div><div className="text-xs text-muted">Créé le {fmt(h.created_at)}</div></div><div className="text-sm">{h.members} membre{h.members!==1?"s":""}</div></div>)}</div></article><article className="bg-[#22301F] text-[#F0EFE6] rounded-2xl p-5"><div className="font-mono text-xs text-[#D8A94A]">LECTURE TRACTION</div><h3 className="font-serif text-xl mt-3">À suivre en priorité</h3><p className="text-sm opacity-80 mt-3 leading-relaxed">Croissance seule ne suffit pas. Les prochaines briques mesureront activation, rétention J7/J30, WAU/MAU et cohortes avant de les présenter comme KPI investisseurs.</p><div className="mt-5 border-t border-white/20 pt-4 text-xs opacity-70">Données actualisées : {new Date(data.generatedAt).toLocaleString("fr-BE")}</div></article></section></>}
 {data&&tab!=="overview"&&<><div className="relative mb-5"><Search size={17} className="absolute left-4 top-3.5 text-muted"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={tab==="users"?"Rechercher un nom, e-mail ou foyer…":"Rechercher un foyer ou un membre…"} className="w-full bg-paper border border-border rounded-xl py-3 pl-11 pr-4 outline-none"/></div>{tab==="users"?<div className="space-y-3">{users.map(u=><article key={u.id} className="bg-paper border border-border rounded-2xl p-5 grid md:grid-cols-[1.2fr_1fr_.7fr] gap-4"><div><div className="font-semibold text-lg">{u.firstName}</div><div className="text-sm text-muted break-all">{u.email||"E-mail indisponible"}</div><div className="text-xs text-muted mt-2">Arrivée : {fmt(u.joinedAt)}</div></div><div><div className="text-xs uppercase tracking-wide text-muted mb-2">Foyers · {u.households.length}</div>{u.households.map(h=><div key={h.id} className="text-sm mb-1"><b>{h.name}</b> · {h.role==="creator"?"Créateur":"Membre"}</div>)}</div><div><span className={`inline-flex rounded-full px-2.5 py-1 text-xs ${active30(u.lastActivity)?"bg-mustardBg text-ink":"bg-[#E7E3D8] text-muted"}`}>{active30(u.lastActivity)?"Actif · 30 j":"Inactif · 30 j"}</span><div className="text-xs text-muted mt-3">Dernière activité<br/>{fmt(u.lastActivity)}</div></div></article>)}{!users.length&&<div className="bg-paper border border-border rounded-2xl p-6 text-muted">Aucun utilisateur trouvé.</div>}</div>:<div className="space-y-3">{homes.map(h=><article key={h.id} className="bg-paper border border-border rounded-2xl p-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="font-semibold text-lg">{h.name}</div><div className="text-xs text-muted mt-1">Créé le {fmt(h.createdAt)} · {h.members.length} membre{h.members.length!==1?"s":""}</div></div><span className={`h-fit rounded-full px-2.5 py-1 text-xs ${active30(h.lastActivity)?"bg-mustardBg":"bg-[#E7E3D8] text-muted"}`}>{active30(h.lastActivity)?"Actif · 30 j":"Inactif · 30 j"}</span></div><div className="grid md:grid-cols-2 gap-5 mt-5 pt-4 border-t border-border"><div>{h.members.map(m=><div key={m.id} className="text-sm mb-2"><b>{m.firstName}</b> <span className="text-muted">· {m.role==="creator"?"Créateur":"Membre"}{m.email?` · ${m.email}`:""}</span></div>)}</div><div className="grid grid-cols-3 gap-2 text-center"><div><b>{h.tasks30}</b><div className="text-xs text-muted">Tâches · 30 j</div></div><div><b>{h.shopping30}</b><div className="text-xs text-muted">Courses · 30 j</div></div><div><b>{h.events30}</b><div className="text-xs text-muted">Événements · 30 j</div></div></div></div></article>)}{!homes.length&&<div className="bg-paper border border-border rounded-2xl p-6 text-muted">Aucun foyer trouvé.</div>}</div>}</>}
 </div></main>;
}
