export type LobaInsight = { title: string; observation: string; action: string; metric: string };
export type FunnelPoint = { step: string; value: number };
export type LobaContext = {
  growth?: { users7?: { current:number; previous:number; rate:number|null; comparable:boolean }; households7?: { current:number; previous:number; rate:number|null; comparable:boolean } };
  retention?: { measuredSignups:number; j1:{rate:number;eligible:number;sufficient:boolean}; j7:{rate:number;eligible:number;sufficient:boolean}; j30:{rate:number;eligible:number;sufficient:boolean} };
  acquisition?: { measuredVisitors:number; measuredSignups:number; attributedVisits:number; attributedSignups:number } | null;
};
export type LobaAnalysis = { facts:string[]; ratios:{id:string;label:string;numerator:number;denominator:number;rate:number;loss:number;comparable:boolean}[]; gaps:string[]; strongestSignal:string; recommendation:string };
const pct=(n:number,d:number)=>(d>0?Math.round((n/d)*100):0);
export function buildLobaAnalysis(kpis:Record<string,number>):LobaAnalysis{
 const users=kpis.users??0, usersWith=Math.max(0,users-(kpis.accountsWithoutHousehold??0)), households=kpis.households??0, active=kpis.activeHouseholds30??0, ambassadors=kpis.shareUsers30??0;
 const activation=pct(usersWith,users), activity=pct(active,households), ambassadorRate=pct(ambassadors,users);
 const ratios=[{id:"account-household",label:"Compte → foyer",numerator:usersWith,denominator:users,rate:activation,loss:Math.max(0,users-usersWith),comparable:true},{id:"household-active",label:"Foyers actifs · 30 j",numerator:active,denominator:households,rate:activity,loss:Math.max(0,households-active),comparable:true},{id:"ambassadors",label:"Utilisateurs ambassadeurs · 30 j",numerator:ambassadors,denominator:users,rate:ambassadorRate,loss:Math.max(0,users-ambassadors),comparable:false}];
 const weakest=ratios.slice(0,2).filter(x=>x.denominator>0).sort((a,b)=>a.rate-b.rate)[0];
 return {facts:[`${users} compte${users===1?"":"s"} DABO inscrit${users===1?"":"s"}.`,`${usersWith} compte${usersWith===1?"":"s"} rattaché${usersWith===1?"":"s"} à au moins un foyer (${activation}%).`,`${active} foyer${active===1?"":"s"} actif${active===1?"":"s"} sur ${households} sur les 30 derniers jours (${activity}%).`,`${ambassadors} ambassadeur${ambassadors===1?"":"s"} sur 30 jours et ${kpis.shares30??0} partage${(kpis.shares30??0)===1?"":"s"} enregistré${(kpis.shares30??0)===1?"":"s"}.`],ratios,gaps:["Les cohortes J1/J7/J30 ne deviennent présentables qu’après maturité et avec un échantillon suffisant.","Compte → foyer mesure des utilisateurs, tandis que foyers actifs mesure des foyers : ces unités ne forment pas une conversion séquentielle directe.","Les petits volumes d’acquisition restent exploratoires."],strongestSignal:weakest?`${weakest.label} est le ratio mesurable le plus faible : ${weakest.rate}% (${weakest.numerator}/${weakest.denominator}).`:"Données insuffisantes pour identifier un signal dominant.",recommendation:weakest?.id==="household-active"?"Priorité : comprendre les foyers créés mais inactifs avant toute relance, en segmentant par ancienneté et dernier usage.":"Priorité : réduire la friction entre inscription et rattachement au premier foyer."};
}
function investorBrief(k:Record<string,number>,c?:LobaContext){
 const a=buildLobaAnalysis(k), g=c?.growth?.users7, hg=c?.growth?.households7, r=c?.retention, ac=c?.acquisition;
 const growth=g?.comparable?`Sur 7 jours, les nouveaux comptes évoluent de ${g.rate!>=0?"+":""}${g.rate}% (${g.current} vs ${g.previous})`:"La croissance des comptes n’a pas encore de base comparable suffisante";
 const homeGrowth=hg?.comparable?`et les nouveaux foyers de ${hg.rate!>=0?"+":""}${hg.rate}% (${hg.current} vs ${hg.previous}).`:`et la croissance des foyers reste à contextualiser.`;
 const retention=r&&r.j1.sufficient?`La rétention J1 mesurée est de ${r.j1.rate}% sur ${r.j1.eligible} inscrits éligibles.`:"La rétention est encore en cours de mesure et ne doit pas être présentée comme une preuve de fidélité.";
 const acquisition=ac?`L’acquisition instrumentée compte ${ac.measuredVisitors} visiteur(s) et ${ac.measuredSignups} inscription(s) ; ce volume reste exploratoire.`:"L’acquisition n’est pas encore suffisamment mesurée.";
 return `Résumé présentable : ${k.users??0} comptes, ${k.households??0} foyers, ${k.accountToHouseholdRate??0}% des comptes rattachés à un foyer et ${k.activeHouseholds30??0} foyers actifs sur 30 jours. ${growth} ${homeGrowth} ${k.tasksCompleted30??0} tâches terminées, ${k.shoppingBought30??0} achats et ${k.eventsCreated30??0} événements ont été enregistrés sur 30 jours. ${retention} ${acquisition} À présenter comme traction précoce, sans extrapoler au-delà des données disponibles.`;
}
export function answerLobaAdmin(question:string,kpis:Record<string,number>,insights:LobaInsight[],funnel:FunnelPoint[],context?:LobaContext){
 const q=question.toLocaleLowerCase("fr"), a=buildLobaAnalysis(kpis), users=kpis.users??0, without=kpis.accountsWithoutHousehold??0, activation=kpis.accountToHouseholdRate??0;
 if(/investisseur|banque|incubateur|pitch|présentation|presentation|résumé.*externe|resume.*externe/.test(q)) return investorBrief(kpis,context);
 if(/comment va|santé|sante|situation|diagnostic|état|etat|résumé|resume|kpi/.test(q)){const g=context?.growth?.households7;const trend=g?.comparable?` Les créations de foyers sur 7 jours évoluent de ${g.rate!>=0?"+":""}${g.rate}% (${g.current} vs ${g.previous}).`:"";return `État de DABO : ${a.facts.join(" ")}${trend} ${a.strongestSignal} ${a.recommendation}`;}
 if(/inqui|risque|alerte|attention|surveill/.test(q)){const g=context?.growth?.households7;const trend=g?.comparable&&g.rate!==null&&g.rate<0?`La création de foyers recule de ${g.rate}% sur 7 jours (${g.current} vs ${g.previous}). `:"";return `${trend}${a.strongestSignal} La rétention et l’acquisition restent trop jeunes pour conclure fortement. Je surveillerais d’abord l’activité des foyers, puis la création de foyers, sans confondre signal court terme et tendance durable.`;}
 if(/funnel|entonnoir|parcours|perd|perte|rupture|conversion/.test(q)){if((kpis.attributedVisits??0)>0){const e1=kpis.retentionJ1Eligible??context?.retention?.j1.eligible??0; const r1=kpis.retentionJ1??context?.retention?.j1.rate??0; const retention=e1>0?` Rétention disponible : J1 ${r1}% (${e1} éligibles).`:""; return `Funnel attribué : ${kpis.attributedVisits??0} visite(s) via partage → ${kpis.attributedSignups??0} inscription(s) → ${kpis.attributedHouseholds??0} foyer(s) → ${kpis.attributedFirstValue??0} première(s) valeur(s).${retention} L’échantillon reste faible : je n’en déduis pas encore un taux de conversion généralisable.`;}return `${a.strongestSignal} Je ne considère pas compte → foyer puis foyer actif comme un seul funnel car les unités diffèrent. Le parcours attribué partage → visite → inscription → foyer → première valeur doit accumuler davantage de données. Les cohortes J1/J7/J30 doivent aussi mûrir avant toute conclusion.`;}
 if(/activation|sans foyer|pas.*foyer|combien.*foyer|inscri.*foyer/.test(q))return `DABO compte ${users} utilisateurs. ${without} compte${without===1?"":"s"} ${without===1?"n’est":"ne sont"} rattaché${without===1?"":"s"} à aucun foyer : ${users-without}/${users} sont rattachés, soit ${activation}%.`;
 if(/rétention|retention|revien|cohorte|j1|j7|j30/.test(q)){const r=context?.retention;if(r?.j1.sufficient)return `Rétention : J1 ${r.j1.rate}% (${r.j1.eligible} éligibles), J7 ${r.j7.sufficient?`${r.j7.rate}% (${r.j7.eligible} éligibles)`:"en cours de mesure"}, J30 ${r.j30.sufficient?`${r.j30.rate}% (${r.j30.eligible} éligibles)`:"en cours de mesure"}. Je garde séparé “foyers actifs · 30 j”, qui mesure l’activité globale.`;return `La rétention J1/J7/J30 est instrumentée mais reste en cours de mesure. ${kpis.activeHouseholds30??0}/${kpis.households??0} foyers sont actifs sur 30 jours (${a.ratios[1].rate}%), ce qui est un indicateur d’activité, pas un taux de rétention.`;}
 if(/priorité|priorite|faire aujourd|cette semaine|recommande|améliorer|ameliorer/.test(q)){const top=insights.slice(0,2);return `${a.strongestSignal} ${a.recommendation}${top.length?` Signaux complémentaires : ${top.map((x,i)=>`${i+1}. ${x.title}`).join(" ; ")}.`:""} Je recommande une seule expérience mesurable à la fois, puis comparaison avant/après.`;}
 if(/croissance|grandir|acquisition|connaître|campagne|ramener|utilisateur/.test(q)){const g=context?.growth?.users7,h=context?.growth?.households7;return `Croissance : ${g?.comparable?`comptes 7 j ${g.rate!>=0?"+":""}${g.rate}% (${g.current} vs ${g.previous})`:"comptes 7 j sans base comparable"} ; ${h?.comparable?`foyers 7 j ${h.rate!>=0?"+":""}${h.rate}% (${h.current} vs ${h.previous})`:"foyers 7 j sans base comparable"}. Activation compte → foyer : ${activation}%. Je testerais d’abord une action d’acquisition mesurable à faible pression, sans automatiser une campagne avant preuve d’effet.`;}
 if(/donnée|donnee|mesur|sais-tu|disponible|manque|fiable/.test(q))return `Je peux exploiter comptes, foyers, activité 7/30 j, tâches, courses, événements, multi-foyers, partages, croissance, acquisition attribuée et cohortes de rétention. Limites : ${a.gaps.join(" ")}`;
 return `Je peux maintenant répondre comme copilote du cockpit. Demande-moi : “Comment va DABO ?”, “Qu’est-ce qui m’inquiète ?”, “Quelle est ma priorité cette semaine ?”, “Où perd-on des utilisateurs ?” ou “Prépare un résumé pour un investisseur”. Je sépare toujours faits, signaux et hypothèses.`;
}
