import test from "node:test";
import assert from "node:assert/strict";
import {detectHouseholdDomain,routeHouseholdContext} from "../lib/loba-household-context-router";
import type {LobaHouseholdContext} from "../lib/loba-household-ai";

const many=(n:number,fn:(i:number)=>any)=>Array.from({length:n},(_,i)=>fn(i));
const context:LobaHouseholdContext={household:{id:"h",name:"Foyer"},currentMember:{id:"m",firstName:"Ray",language:"fr"},members:[{id:"m",firstName:"Ray"}],tasks:many(100,i=>({id:`t${i}`,name:`T ${i}`,status:"pending",urgent:false,dueDate:null,assignedTo:null,durationKey:null,effortLevel:null,routineId:null})),shopping:many(100,i=>({id:`s${i}`,name:`S ${i}`,quantity:null,urgent:false,dueDate:null,assignedTo:null})),events:many(100,i=>({id:`e${i}`,title:`E ${i}`,eventDate:"2026-09-10",recurring:false,visibility:"household" as const})),balance:[{memberId:"m",firstName:"Ray",points30d:10}],finance:{currency:"EUR",month:{start:"2026-09-01",endExclusive:"2026-10-01",spent:100,pendingBills:20,commitments:120,byCategory:{courses:50},transactionCount:3},year:{start:"2026-01-01",endExclusive:"2027-01-01",spent:500,transactionCount:12},pendingBills:many(100,i=>({id:`b${i}`,label:`B ${i}`,amount:10,category:"autre",dueOn:"2026-09-20",visibility:"household" as const,updatedAt:"2026-09-10"})),budgets:many(30,i=>({category:`c${i}`,monthlyReference:100})),recentTransactions:many(100,i=>({label:`D ${i}`,amount:5,category:"autre",occurredOn:"2026-09-10",paidBy:"m",visibility:"household" as const}))},generatedAt:"2026-09-10T00:00:00Z"};

test("LOBA route une question Finance vers un contexte Finance compact",()=>{const d=detectHouseholdDomain("Combien avons-nous dépensé ce mois-ci ?");assert.equal(d,"finance");const c=routeHouseholdContext(context,d);assert.equal(c.tasks.length,0);assert.equal(c.shopping.length,0);assert.equal(c.events.length,0);assert.equal(c.finance?.month.spent,100);assert.equal(c.finance?.recentTransactions.length,20);assert.equal(c.finance?.pendingBills.length,30)});
test("LOBA conserve les IDs du domaine utile sans envoyer tout le foyer",()=>{const c=routeHouseholdContext(context,detectHouseholdDomain("Supprime la tâche T 4"));assert.equal(c.tasks.length,40);assert.equal(c.shopping.length,0);assert.equal(c.finance,undefined)});
test("LOBA borne aussi le contexte transversal",()=>{const c=routeHouseholdContext(context,"general");assert.equal(c.tasks.length,15);assert.equal(c.shopping.length,15);assert.equal(c.events.length,15);assert.equal(c.finance?.recentTransactions.length,10);assert.equal(c.finance?.pendingBills.length,10)});
test("une question sur les dépenses de courses reste Finance",()=>{assert.equal(detectHouseholdDomain("Combien avons-nous dépensé en courses ce mois-ci ?"),"finance")});
test("la question courante prime sur un ancien sujet Finance",()=>{assert.equal(detectHouseholdDomain("Supprime la tâche T 4",[{role:"user",content:"Combien avons-nous dépensé ?"}]),"tasks")});
