import { DURATION_OPTIONS, EFFORT_OPTIONS, computeTaskPoints } from "@/lib/types";

export type LobaShoppingAddAction={type:"shopping.add";item:string;quantity:string|null};
export type LobaTaskAddAction={type:"task.add";name:string;dueDate:string|null;assignedTo:string|null;urgent:boolean;durationKey:string;effortLevel:string};
export type LobaCalendarAddAction={type:"calendar.add";title:string;eventDate:string;visibility:"household"|"personal";recurring:false};
export type LobaTaskUpdateAction={type:"task.update";taskId:string;changes:{name?:string;dueDate?:string|null;assignedTo?:string|null;urgent?:boolean;durationKey?:string;effortLevel?:string};expected?:Record<string,unknown>;taskName?:string;changeSummary?:string};
export type LobaTaskDeleteAction={type:"task.delete";taskId:string;expected?:Record<string,unknown>;taskName?:string};
export type LobaShoppingUpdateAction={type:"shopping.update";itemId:string;changes:{name?:string;quantity?:string|null;dueDate?:string|null;assignedTo?:string|null;urgent?:boolean};expected?:Record<string,unknown>;itemName?:string;changeSummary?:string};
export type LobaShoppingDeleteAction={type:"shopping.delete";itemId:string;expected?:Record<string,unknown>;itemName?:string};
export type LobaCalendarUpdateAction={type:"calendar.update";eventId:string;changes:{title?:string;eventDate?:string};expected?:Record<string,unknown>;eventTitle?:string;visibility?:"household"|"personal";changeSummary?:string};
export type LobaCalendarDeleteAction={type:"calendar.delete";eventId:string;expected?:Record<string,unknown>;eventTitle?:string;visibility?:"household"|"personal"};
export const LOBA_FINANCE_CATEGORIES=["courses","logement","energie","transport","abonnements","sante","enfants","loisirs","maison","autre"] as const;
export type LobaFinanceCategory=typeof LOBA_FINANCE_CATEGORIES[number];
export type LobaFinanceExpenseAddAction={type:"finance.expense.add";label:string;amount:number;category:LobaFinanceCategory;occurredOn:string;paidBy:string};
export type LobaFinanceBillAddAction={type:"finance.bill.add";label:string;amount:number;category:LobaFinanceCategory;dueOn:string};
export type LobaFinanceBillPayAction={type:"finance.bill.pay";billId:string;paidBy:string;paidOn:string;expected?:Record<string,unknown>;billLabel?:string};
export type LobaHouseholdAction=LobaShoppingAddAction|LobaTaskAddAction|LobaCalendarAddAction|LobaTaskUpdateAction|LobaTaskDeleteAction|LobaShoppingUpdateAction|LobaShoppingDeleteAction|LobaCalendarUpdateAction|LobaCalendarDeleteAction|LobaFinanceExpenseAddAction|LobaFinanceBillAddAction|LobaFinanceBillPayAction;

function cleanText(v:unknown,max:number){return typeof v==="string"?v.trim().replace(/\s+/g," ").slice(0,max):""}
function validCivilDate(v:unknown):string|null|undefined{if(v===null||v==="")return null;if(typeof v!=="string"||!/^\d{4}-\d{2}-\d{2}$/.test(v))return undefined;const[y,m,d]=v.split("-").map(Number),dt=new Date(Date.UTC(y,m-1,d));return dt.getUTCFullYear()===y&&dt.getUTCMonth()===m-1&&dt.getUTCDate()===d?v:undefined}
function id(v:unknown){return cleanText(v,100)}
function nullableId(v:unknown):string|null|undefined{if(v===null||v==="")return null;const x=id(v);return x||undefined}
function money(v:unknown):number|undefined{if(typeof v!=="number"||!Number.isFinite(v)||v<=0||v>9999999999.99)return undefined;return Math.round((v+Number.EPSILON)*100)/100}
function financeCategory(v:unknown):LobaFinanceCategory|undefined{return typeof v==="string"&&(LOBA_FINANCE_CATEGORIES as readonly string[]).includes(v)?v as LobaFinanceCategory:undefined}
function expected(v:unknown){return v&&typeof v==="object"&&!Array.isArray(v)?v as Record<string,unknown>:undefined}
function normalizeTaskChanges(v:unknown){if(!v||typeof v!=="object")return null;const r=v as Record<string,unknown>,o:LobaTaskUpdateAction["changes"]={};if("name" in r){const x=cleanText(r.name,160);if(!x)return null;o.name=x}if("dueDate" in r){const x=validCivilDate(r.dueDate);if(x===undefined)return null;o.dueDate=x}if("assignedTo" in r){const x=nullableId(r.assignedTo);if(x===undefined)return null;o.assignedTo=x}if("urgent" in r){if(typeof r.urgent!=="boolean")return null;o.urgent=r.urgent}if("durationKey" in r){const x=cleanText(r.durationKey,20);if(!DURATION_OPTIONS.some(d=>d.key===x))return null;o.durationKey=x}if("effortLevel" in r){const x=cleanText(r.effortLevel,20);if(!EFFORT_OPTIONS.some(e=>e.key===x))return null;o.effortLevel=x}return Object.keys(o).length?o:null}
function normalizeShoppingChanges(v:unknown){if(!v||typeof v!=="object")return null;const r=v as Record<string,unknown>,o:LobaShoppingUpdateAction["changes"]={};if("name" in r){const x=cleanText(r.name,160);if(!x)return null;o.name=x}if("quantity" in r)o.quantity=cleanText(r.quantity,80)||null;if("dueDate" in r){const x=validCivilDate(r.dueDate);if(x===undefined)return null;o.dueDate=x}if("assignedTo" in r){const x=nullableId(r.assignedTo);if(x===undefined)return null;o.assignedTo=x}if("urgent" in r){if(typeof r.urgent!=="boolean")return null;o.urgent=r.urgent}return Object.keys(o).length?o:null}
function normalizeCalendarChanges(v:unknown){if(!v||typeof v!=="object")return null;const r=v as Record<string,unknown>,o:LobaCalendarUpdateAction["changes"]={};if("title" in r){const x=cleanText(r.title,160);if(!x)return null;o.title=x}if("eventDate" in r){const x=validCivilDate(r.eventDate);if(!x)return null;o.eventDate=x}return Object.keys(o).length?o:null}

export function normalizeHouseholdAction(value:unknown):LobaHouseholdAction|null{if(!value||typeof value!=="object")return null;const r=value as Record<string,unknown>;
 if(r.type==="shopping.add"){const item=cleanText(r.item,160);if(!item)return null;return{type:"shopping.add",item,quantity:cleanText(r.quantity,80)||null}}
 if(r.type==="task.add"){const name=cleanText(r.name,160),dueDate=validCivilDate(r.dueDate),assignedTo=nullableId(r.assignedTo),durationKey=cleanText(r.durationKey,20),effortLevel=cleanText(r.effortLevel,20);if(!name||dueDate===undefined||assignedTo===undefined||typeof r.urgent!=="boolean"||!DURATION_OPTIONS.some(x=>x.key===durationKey)||!EFFORT_OPTIONS.some(x=>x.key===effortLevel))return null;return{type:"task.add",name,dueDate,assignedTo,urgent:r.urgent,durationKey,effortLevel}}
 if(r.type==="calendar.add"){const title=cleanText(r.title,160),eventDate=validCivilDate(r.eventDate),visibility=r.visibility==="household"||r.visibility==="personal"?r.visibility:null;if(!title||!eventDate||!visibility||r.recurring!==false)return null;return{type:"calendar.add",title,eventDate,visibility,recurring:false}}
 if(r.type==="task.update"){const taskId=id(r.taskId),changes=normalizeTaskChanges(r.changes);if(!taskId||!changes)return null;return{type:"task.update",taskId,changes,expected:expected(r.expected),taskName:cleanText(r.taskName,160)||undefined,changeSummary:cleanText(r.changeSummary,500)||undefined}}
 if(r.type==="task.delete"){const taskId=id(r.taskId);if(!taskId)return null;return{type:"task.delete",taskId,expected:expected(r.expected),taskName:cleanText(r.taskName,160)||undefined}}
 if(r.type==="shopping.update"){const itemId=id(r.itemId),changes=normalizeShoppingChanges(r.changes);if(!itemId||!changes)return null;return{type:"shopping.update",itemId,changes,expected:expected(r.expected),itemName:cleanText(r.itemName,160)||undefined,changeSummary:cleanText(r.changeSummary,500)||undefined}}
 if(r.type==="shopping.delete"){const itemId=id(r.itemId);if(!itemId)return null;return{type:"shopping.delete",itemId,expected:expected(r.expected),itemName:cleanText(r.itemName,160)||undefined}}
 if(r.type==="calendar.update"){const eventId=id(r.eventId),changes=normalizeCalendarChanges(r.changes);if(!eventId||!changes)return null;const visibility=r.visibility==="household"||r.visibility==="personal"?r.visibility:undefined;return{type:"calendar.update",eventId,changes,expected:expected(r.expected),eventTitle:cleanText(r.eventTitle,160)||undefined,visibility,changeSummary:cleanText(r.changeSummary,500)||undefined}}
 if(r.type==="calendar.delete"){const eventId=id(r.eventId);if(!eventId)return null;const visibility=r.visibility==="household"||r.visibility==="personal"?r.visibility:undefined;return{type:"calendar.delete",eventId,expected:expected(r.expected),eventTitle:cleanText(r.eventTitle,160)||undefined,visibility}}
 if(r.type==="finance.expense.add"){const label=cleanText(r.label,120),amount=money(r.amount),category=financeCategory(r.category),occurredOn=validCivilDate(r.occurredOn),paidBy=id(r.paidBy);if(!label||amount===undefined||!category||!occurredOn||!paidBy)return null;return{type:"finance.expense.add",label,amount,category,occurredOn,paidBy}}
 if(r.type==="finance.bill.add"){const label=cleanText(r.label,120),amount=money(r.amount),category=financeCategory(r.category),dueOn=validCivilDate(r.dueOn);if(!label||amount===undefined||!category||!dueOn)return null;return{type:"finance.bill.add",label,amount,category,dueOn}}
 if(r.type==="finance.bill.pay"){const billId=id(r.billId),paidBy=id(r.paidBy),paidOn=validCivilDate(r.paidOn);if(!billId||!paidBy||!paidOn)return null;return{type:"finance.bill.pay",billId,paidBy,paidOn,expected:expected(r.expected),billLabel:cleanText(r.billLabel,120)||undefined}}
 return null}
export function taskActionPoints(a:LobaTaskAddAction){return computeTaskPoints(a.durationKey,a.effortLevel)}
export function parseLobaHouseholdEnvelope(raw:string){const fallback={answer:raw.trim(),proposedAction:null as LobaHouseholdAction|null};try{const p=JSON.parse(raw) as Record<string,unknown>,answer=typeof p.answer==="string"?p.answer.trim():"";return answer?{answer,proposedAction:normalizeHouseholdAction(p.proposedAction)}:fallback}catch{return fallback}}
